/** Canonical schema for data/raw/raw_discoveries.csv */

export const RAW_DISCOVERIES_COLUMNS = [
  'business_id',
  'company_name',
  'sector',
  'city',
  'county',
  'source',
  'website',
  'founded_year',
  'evidence_urls',
  'google_rating',
  'google_review_count',
  'institutional_refs',
  'branches',
  'warehouses',
  'distribution_coverage',
  'new_locations',
  'hiring_visible',
  'exports',
  'new_products',
  'vc_funded',
  'accelerator_alumni',
  'media_featured',
  'linkedin_heavy',
  'is_startup',
  'status',
  'added_date',
];

export const RAW_DISCOVERIES_DEFAULTS = {
  sector: '',
  city: '',
  county: '',
  source: 'Manual discovery',
  website: '',
  founded_year: '',
  evidence_urls: '',
  google_rating: '',
  google_review_count: '0',
  institutional_refs: '0',
  branches: '0',
  warehouses: '0',
  distribution_coverage: 'local',
  new_locations: '0',
  hiring_visible: 'False',
  exports: 'False',
  new_products: '0',
  vc_funded: 'False',
  accelerator_alumni: 'False',
  media_featured: 'False',
  linkedin_heavy: 'False',
  is_startup: 'False',
  status: 'Discovered',
};
